#!/usr/bin/env   zsh

runname=`basename $0`

case $runname in
    brew | abrew)
        eval $(/opt/Homebrew/bin/brew shellenv) #ckbrew

        abrew () {
            arch -arm64e /opt/homebrew/bin/brew $@
        } 
        ;;
    xbrew)
        eval $(/usr/local/Homebrew/bin/brew shellenv) #ckbrew

        xbrew () {
            arch -x86_64 /usr/local/bin/brew $@
        }
        ;;
esac

abrewup () {
    abrew update && abrew upgrade && abrew cu -a -f -y && /opt/homebrew/bin/mas upgrade
}

abrewin () {
    arch -arm64e /bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"
}

abrewun () {
  arch -arm64e /bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/HomebrewUninstall.sh)"
}

abrewclean () {
  abrew ls --$1 | xargs brew remove -f --ignore-dependencies
}

brewup-b () {
    brew update && brew upgrade && brew cu -a -f -y && /opt/homebrew/bin/mas upgrade
}

bin () {
    brew install $1 -v --force
}

bcin () {
    brew install $1 -v --force --cask
}

brewun () {
  arch -arm64e /bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/HomebrewUninstall.sh)"
}

brewclean () {
  brew ls --$1 | xargs brew remove -f --ignore-dependencies
}

xbi () {
    xbrew install $1
}

xbrewup () {
    xbrew update && xbrew upgrade && xbrew cu -a -f -y && arch -x86_64 /usr/local/bin/mas upgrade
}

brewin () {
  arch -x86_64 /bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"
}

xbrewun () {
  arch -x86_64 /bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/HomebrewUninstall.sh)"
}

xbrewclean () {
  xbrew ls --$1 | xargs brew remove -f --ignore-dependencies
}

brewup () {
    case $runname in
        abrew)
            abrewup
            ;;
        brew)
            brewup-b
            ;;
        xbrew)
            xbrewup
            ;;
    esac
}

brewclean () {
    brew ls --$1 | xargs brew remove -f --ignore-dependencies
}

#-------------------------------------------
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles #ckbrew
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_ENV_HINTS=1

