#!/usr/bin/env zsh
#-----------------------------------------------------------------------
# This script is to iniatize python environment
#---
# Author: Hao Feng (F1)
#
# Init Date:   Apr. 21, 2022
# last Date:   Apr. 01, 2023
#
# Copyright (c) 2022, RDS
#
#---
# For Apple M1 Silicon CPU:
#   - arm:
#       ai:       AI envs
#       bd:       Baidu AI: paddle
#       cloud:    Cloud envs
#       dcm:      dcm conda environment with arm64
#       fpa:      Fatavay Physics based AI
#       mbforge:  mambaforge
#   - x86_64:
#       rconda:   ROS envs
#-----------------------------------------------------------------------

create_conda () {                                        
    name=$1                                              
                                                         
    if [[ ! -f $name ]]; then                            
        init_conda $condabase
        conda create -y -p $name python=3.10
    fi                                                   
                                                         
    conda activate $name                                 
    conda config --env --add channels conda-forge        

    # - two important tools
    conda install -y mamba -c conda-forge                
#   pip install pip-review -y
}                                                        
                                                         
#----------------
init_conda () {
    env=$1

    if [[ -f $env/etc/profile.d/conda.sh ]]; then
        source $env/etc/profile.d/conda.sh
        conda activate $env
        condabin=`dirname $CONDA_EXE`
    elif [[ -f $env/bin/activate ]]; then
        source $env/bin/activate
    else
        conda activate $env
        if [ $? -ne 0 ]; then
            echo
            echo "$env does NOT exist, create it firstly."
            echo "----------------------------------------------------"
            echo
            create_conda $env
        fi
    fi
}

#----------------
pipup () {
    pip-review -a
}

#----------------
condauc () {
    conda $1 --all -y
}

#----------------
condaup () {
    condauc update
}

#----------------
condaclean () {
    condauc clean
}

#----------------
acondaup () {
    conda update anaconda --all -y
}

#----------------
conda_export () {
    conda env export --no-builds | grep -v "^prefix: " > $1
}

#----------------
conda_from_file () {
    mamba env update --file $1
}

#----------------
cdea () {
    conda deactivate
}

#----------------
cact () {
    conda activate $1
}

#----------------
cinfo () {
    conda info
}

#----------------
cel () {
    conda env list
}

#----------------
jnb () {
    $condabin/jupyter-notebook
}

#----------------
jlab () {
    $condabin/jupyter-lab
}

#----#----------------
install_conda_basic () {                                 
    basic=(jupyter matplotlib numpy pandas scipy seaborn)
    mamba install -y -c conda-forge ${basic[@]}          
}                                                        

#----------------
pyenv () {
    python -m venv $1
}

#---------------------------------------------------------
# main function

runname=`basename $0`
os=`uname`

conda_home=/opt/conda
ai_home=/opt/conda/AI
ros_home=/opt/ros/conda_venv

if [[ $os == Darwin ]]; then
  condabase=${conda_home}/mambaforge
elif [[ $os == Linux ]]; then
  condabase=${conda_home}/miniconda3
fi

condash=$condabase/etc/profile.d/conda.sh

if [[ -f $condash ]]; then
    source $condash
    conda activate $env
fi

case $runname in
    ai | aiconda)
        export condaenv=${ai_home}
        ;;
    bd | cloud | fpa | mbforge)
        export condaenv=${conda_home}/$runname
        ;;
    dcm)
        export condaenv=/Users/fengh/Research/FORECAST/DCM/envs
        ;;
    rconda)
        export condaenv=${ros_home}
        ;;
    *)
        export condaenv=${conda_home}/anaconda3
        ;;
esac

export PATH=${condaenv}/bin:$PATH
init_conda $condaenv
