#!/usr/bin/env zsh
#
runname=`basename $0`

case $runname in
    d2m)
        d2m () {
            pandoc -f docx -t markdown --extract-media=$1 -o $1.md $1.docx
        }
        m2d () {
            pandoc $1.md -o $1.docx
        }
        ;;
    w2m)
        eval "$(rbenv init -)"
        
        export PATH="/opt/homebrew/lib/ruby/gems/3.0.0/bin:/opt/homebrew/opt/ruby/bin:$PATH"
        export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"
        export PKG_CONFIG_PATH="/opt/homebrew/opt/ruby/lib/pkgconfig"
        ;;
    *)
        ;;
esac
