#!/usr/bin/env zsh

runname=`basename $0`

abrew () {
    arch -arm64e /opt/homebrew/bin/brew $@
}

case $runname in
    mysql)
        sql () {
          abrew services $1 mysql
        }

        sqlstart () {
          sql start
        }

        sqlstop () {
          sql stop
        }

        sqlstart
        ;;
    redis)
        redis () {
          abrew services $1 redis
        }

        redisstart () {
          redis start
        }

        redisstart
        ;;
esac
