#!/usr/bin/env zsh

runname=`basename $0`

abrew () {
    arch -arm64e /opt/homebrew/bin/brew $@
}

case $runname in
    mysql)
        mysql.server start

        sql () {
            abrew services $1 mysql
        }

        sqls () {
            mysql.server $1
        }

        sqlr () {
            mysql -u root -p
        }
        ;;
    redis)
        redis () {
            abrew services $1 redis
        }
        ;;
esac
