#!/usr/bin/env zsh

runname=`basename $0`

abrew () {
    arch -arm64e /opt/homebrew/bin/brew $@
}

case $runname in
    mysql)
        sql () {
          abrew services $1 mysql
        }

        sqls () {
          sql start
        }

        sqlr () {
          sql restart
        }

        sqlstop () {
          sql stop
        }

        sqls
        ;;
    redis)
        redis () {
          abrew services $1 redis
        }

        rediss () {
          redis start
        }

        redisr () {
          redis restart
        }

        redisstop () {
          redis stop
        }

        rediss
        ;;
esac
