#!/usr/bin/env zsh
#
runname=`basename $0`

case $runname in
    github)
        sed -e 's#\[url.*$#\[url \"https://github.com\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    ghproxy)
        sed -e 's#\[url.*$#\[url \"https://ghproxy.com\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    gitclone)
        sed -e 's#\[url.*$#\[url \"https://gitclone.com\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    gitcnp)
        sed -e 's#\[url.*$#\[url \"https://github.com.cnpmjs.org\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    gitfast)
        sed -e 's#\[url.*$#\[url \"https://hub.fastgit.org\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    gitraws)
        sed -e 's#\[url.*$#\[url \"https://https://raw.githubusercontents.com\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    gitseven | git7)
        sed -e 's#\[url.*$#\[url \"https://raw.sevencdn.com\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    *)
        ;;
esac

mv   ~/.gitconfig.tmp    ~/.gitconfig

