#!/usr/bin/env zsh
#
runname=`basename $0`

case $runname in
    gitclone)
        sed -e 's#\[url.*$#\[url \"https://gitclone.com\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    ghproxy)
        sed -e 's#\[url.*$#\[url \"https://ghproxy.com\"]#g' ~/.gitconfig > ~/.gitconfig.tmp
        ;;
    *)
        ;;
esac

mv ~/.gitconfig.tmp .gitconfig

