#!/usr/bin/env zsh
#
runname=`basename $0`

case $runname in
  gitssh)
    git config --global url."git@github.com:".insteadOf "https://github.com/"
    ;;
  githttp)
    git config --global url.https://github.com/.insteadOf ssh://git@github.com
    ;;
esac
