#!/usr/bin/env   bash

os=`uname`
ip0='192.168.10.27'

case $os in
    Darwin)
        export https_proxy=127.0.0.1:9999
        export http_proxy=127.0.0.1:9999
    ;;
    Linux)
        if [ ! -n "$2" ] ;then
           ip=$ip0
        else
           ip=$2
        fi
        echo "proxy ip = $ip"
        export https_proxy=$ip:9999
        export http_proxy=$ip:9999
    ;;
esac
